export const words = [
  { word: "Adaptable", description: "Able to change in order to suit new conditions.", useCase: "An adaptable developer learns new tools without losing focus." },
  { word: "Ambitious", description: "Having a strong desire to achieve something.", useCase: "The team set an ambitious goal for the next release." },
  { word: "Clarity", description: "The quality of being easy to understand.", useCase: "A simple diagram can bring clarity to a complex idea." },
  { word: "Compelling", description: "Evoking strong interest or attention.", useCase: "She opened the presentation with a compelling story." },
  { word: "Consistent", description: "Acting or happening in the same reliable way over time.", useCase: "Consistent practice is more effective than one long study session." },
  { word: "Curious", description: "Eager to know or learn something.", useCase: "A curious mind is always looking for better questions." },
  { word: "Deliberate", description: "Done consciously and intentionally.", useCase: "His deliberate choice of words made the message clearer." },
  { word: "Empathy", description: "The ability to understand another person's feelings.", useCase: "Good product decisions often begin with empathy for the user." },
  { word: "Endeavor", description: "A serious and determined effort to do something.", useCase: "Learning a language is a rewarding long-term endeavor." },
  { word: "Flourish", description: "To grow or develop successfully.", useCase: "New ideas flourish when everyone feels safe to contribute." },
  { word: "Genuine", description: "Sincere, honest, and truly what it appears to be.", useCase: "Her genuine enthusiasm encouraged the entire group." },
  { word: "Insightful", description: "Showing a clear and deep understanding.", useCase: "The research produced several insightful observations." },
  { word: "Nuanced", description: "Characterized by subtle distinctions.", useCase: "The article offers a nuanced view of remote work." },
  { word: "Persistent", description: "Continuing firmly despite difficulty or delay.", useCase: "A persistent learner treats every mistake as useful feedback." },
  { word: "Pragmatic", description: "Solving problems in a practical and realistic way.", useCase: "We took a pragmatic approach and shipped the smallest useful version." },
  { word: "Proficient", description: "Competent or skilled at doing something.", useCase: "She became proficient in English through daily conversation." },
  { word: "Reliable", description: "Consistently good and able to be trusted.", useCase: "A reliable service should handle unexpected traffic safely." },
  { word: "Resilient", description: "Able to recover quickly from difficulties.", useCase: "The resilient team adapted after the original plan changed." },
  { word: "Resourceful", description: "Good at finding quick and clever solutions.", useCase: "The resourceful designer built a prototype with limited tools." },
  { word: "Seamless", description: "Smooth and continuous, with no noticeable gaps.", useCase: "The sign-in experience should feel seamless on every device." },
  { word: "Thoughtful", description: "Showing careful consideration or attention.", useCase: "A thoughtful review can make good work even stronger." },
  { word: "Thrive", description: "To grow, develop, or be successful.", useCase: "Teams thrive when expectations are clear." },
  { word: "Versatile", description: "Able to adapt or be used for many purposes.", useCase: "JavaScript is a versatile language for modern products." },
  { word: "Worthwhile", description: "Important, enjoyable, or useful enough to justify the effort.", useCase: "Building a daily study habit is always worthwhile." }
];
